// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwGZCol4Q1rL14qPVRTLlVekD-z4oATHY',
    appId: '1:67732365698:web:f3a5fc903d09df6ce1ef9b',
    messagingSenderId: '67732365698',
    projectId: 'zoom-clone-5ab3c',
    authDomain: 'zoom-clone-5ab3c.firebaseapp.com',
    storageBucket: 'zoom-clone-5ab3c.appspot.com',
    measurementId: 'G-Z3EYG2VYWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWS_5GlsZmdXzOTBvJwZUPfTpOxsnMoxk',
    appId: '1:67732365698:android:494c2a561c161241e1ef9b',
    messagingSenderId: '67732365698',
    projectId: 'zoom-clone-5ab3c',
    storageBucket: 'zoom-clone-5ab3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTKabV6HD_sk4uNQXfmYvg1Ei9Ae3ogUc',
    appId: '1:67732365698:ios:46a0eb470f3abf8de1ef9b',
    messagingSenderId: '67732365698',
    projectId: 'zoom-clone-5ab3c',
    storageBucket: 'zoom-clone-5ab3c.appspot.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
